name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y build-essential git cmake libboost-all-dev libssl-dev

    - name: Build
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make
        
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          choco install cmake -y
          choco install git -y
          choco install 7zip -y
          choco install visualstudio2019buildtools -y
          choco install boost-msvc-14.2 -y

      - name: Build
        run: |
          git clone https://github.com/HashHound/Dogemone.git
          cd Dogemone
          mkdir build && cd build
          cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release
