name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y build-essential git cmake libboost-all-dev libssl-dev

    - name: Build
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make
        
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: MINGW64

    - name: Install dependencies
      shell: msys2 {0}
      run: |
        pacman -Sy --noconfirm
        pacman -S --noconfirm base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-boost mingw-w64-x86_64-openssl
        pacman -S --noconfirm mingw-w64-x86_64-boost-system mingw-w64-x86_64-boost-regex

    - name: Add MSYS2 to PATH
      run: |
        echo "C:\msys64\usr\bin" >> $GITHUB_PATH
        echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH

    - name: Build
      shell: msys2 {0}
      run: |
        mkdir -p build
        cd build
        cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -Wno-dev -DBOOST_ROOT="C:/msys64/mingw64" ..
        cmake --build . -- -j 2
